run:
  go: '1.22'
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - ineffassign
    - gosimple

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
